# Generated by Django 4.2.7 on 2025-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In-Progress'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
